apiVersion: v1
kind: Service
metadata:
  name: ratus
  labels:
    app: ratus
spec:
  ports:
    - port: 80
  selector:
    app: ratus
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratus
  labels:
    app: ratus
spec:
  selector:
    matchLabels:
      app: ratus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ratus
    spec:
      containers:
        - image: hyperonym/ratus:0.6.1
          name: ratus
          env:
            - name: ENGINE
              value: mongodb
            - name: MONGODB_COLLECTION
              value: tasks
            - name: MONGODB_DATABASE
              value: ratus
            - name: MONGODB_RETENTION_PERIOD
              value: 72h
            - name: MONGODB_URI
              value: mongodb://ratus-mongodb:27017
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /v1/livez
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /v1/readyz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
