name: Codecov

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '4.4'
      - name: Run coverage
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: main
