name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    strategy:
      matrix:
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Test packages
        run: make test
      - name: Build artifacts
        run: make build
