name: MongoDB

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.mongodb-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["4.4", "5.0", "6.0", "7.0"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
          cache-dependency-path: "go.sum"
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Test packages
        run: make test-engine-mongodb
