name: MongoDB

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.mongodb-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.4', '5.0', '6.0']
    defaults:
      run:
        working-directory: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Test packages
        run: make test
