name: MongoDB

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.mongodb-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["4.4", "5.0", "6.0"]
    defaults:
      run:
        working-directory: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "main/go.mod"
          check-latest: true
          cache: true
          cache-dependency-path: "main/go.sum"
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Test packages
        run: make test-engine-mongodb
