name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "main/go.mod"
          check-latest: true
          cache: true
          cache-dependency-path: "main/go.sum"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
      - name: Build artifacts for each target platform
        run: make release
      - name: Upload artifacts
        run: gh release upload ${{ github.ref_name }} release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images to GitHub Container Registry
        run: make github-packages
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push images to Docker Hub
        run: make docker-hub
